import os #IMPORTA BIBLIOTECA OS

from time import sleep #IMPORTA SLEEP DA BIBLIOTECA TIME

TIME = 2 #CIRA VARIÁVEL PARA TEMPO DE ESPERA
INTERATIONS_NUMBER = 3 #CRIA VARIÁVEL PARA NÚMERO DE INTERAÇÕES
DIE_MSG = "2: I gonna die now, bye" #CRIA VARIÁVEL DE TEXTO PARA INTERAÇÃO
ALIVE_MSG = "2: I am alive" #CRIA VARIÁVEL DE TEXTO PÓS INTERAÇÃO
FILENAME = "pid" #CRIA VARIÁVEL DE NOME PARA ARQUIVO

def Open_file(filename): #CRIA FUNÇÃO PARA ABERTURA DO ARQUIVO
    with open(filename, "w") as file: #CRIA E ABRE O ARQUIVO EM MODO DE ESCRITA
        file.write(str(os.getpid())) #OBTÉM VALOR DO PID DO ARQUIVO E TRANSFORMA EM STRING

Open_file(FILENAME) #EXECUTA A FUNÇÃO OPENFILE

for _ in range(INTERATIONS_NUMBER): #CRIA LOOP PARA ESCREVER MENSAGEM 
    print(ALIVE_MSG) #IMPRIME MENSAGEM ALIVE

    sleep(TIME) #AGUARDA TEMPO DE 2 SEGUNDOS

print(DIE_MSG) #IMPRIME MENSAGEM DIE
